# Generated by Django 2.1.3 on 2018-12-04 07:17

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallCenterOp',
            new_name='CallCenterOperator',
        ),
        migrations.RenameModel(
            old_name='OpChief',
            new_name='OperationsChief',
        ),
    ]
