# Generated by Django 2.1.3 on 2018-12-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181205_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='firstName',
            new_name='fName',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='lastName',
            new_name='lName',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='phoneNumber',
            new_name='phoneNum',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='priorityCode',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='streetName',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='timeCalleIn',
            new_name='timeCalledIn',
        ),
        migrations.RenameField(
            model_name='firstresponder',
            old_name='missions',
            new_name='assignedMissionID',
        ),
        migrations.RemoveField(
            model_name='event',
            name='opChief_id',
        ),
        migrations.RemoveField(
            model_name='firstresponder',
            name='location',
        ),
    ]
