# Generated by Django 2.1.3 on 2018-12-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20181208_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='mission_id',
            new_name='mission',
        ),
    ]
