# Generated by Django 2.1.3 on 2018-12-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20181208_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='numberAvailable',
            new_name='quantity',
        ),
    ]
