# Generated by Django 2.1.3 on 2018-12-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20181208_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='events',
            field=models.ManyToManyField(null=True, to='polls.Event'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='missions',
            field=models.ManyToManyField(null=True, to='polls.Mission'),
        ),
    ]
