# Generated by Django 2.1.3 on 2018-12-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20181208_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Event'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='missions',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Mission'),
        ),
    ]
