# Generated by Django 2.1.3 on 2018-12-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20181210_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='ticketDescription',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='ticketType',
            field=models.CharField(blank=True, choices=[('Priority', 'Priority'), ('First Responder', 'First Responder'), ('Equipment', 'Equipment')], max_length=30, null=True),
        ),
    ]
