# Generated by Django 2.1.3 on 2018-12-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20181210_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='ticketStatus',
            field=models.CharField(blank=True, choices=[('Resolved', 'Resolved'), ('Unresolved', 'Unresolved')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='ticketType',
            field=models.CharField(blank=True, choices=[('Priority', 'Priority'), ('First_Responder', 'First_Responder'), ('Equipment', 'Equipment')], max_length=30, null=True),
        ),
    ]
