# Generated by Django 2.1.3 on 2018-12-10 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20181210_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='events',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mission',
        ),
        migrations.AddField(
            model_name='requiredequipment',
            name='equipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Equipment'),
        ),
        migrations.AddField(
            model_name='requiredequipment',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event'),
        ),
    ]
