# Generated by Django 2.1.3 on 2018-12-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20181210_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='lon',
        ),
    ]
