# Generated by Django 2.1.3 on 2018-12-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20181210_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='firstresponder',
            name='assignedMissionID',
        ),
        migrations.AddField(
            model_name='eventstatus',
            name='mission_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Mission'),
        ),
        migrations.AddField(
            model_name='firstresponderstatus',
            name='mission_id',
            field=models.ManyToManyField(blank=True, to='polls.Mission'),
        ),
    ]
