# Generated by Django 2.1.3 on 2018-12-11 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20181210_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstresponderstatus',
            name='mission_id',
        ),
        migrations.AddField(
            model_name='firstresponderstatus',
            name='mission_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Mission'),
            preserve_default=False,
        ),
    ]
