# Generated by Django 2.1.3 on 2018-12-11 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20181210_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstresponderstatus',
            name='mission_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Mission'),
        ),
    ]
